### ISSUE TITLE
Error build : write EPIPE

### ISSUE THREAD

**Issue by ppj34** [elmish/sample-react-counter#4]
Hello,

I have a build error when I run the project on Visual Studio Code (with 'npm start') :

```
> @ start C:\tutorials\fable2-samples-master\minimal
> webpack-dev-server

i ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from ./public
fable-compiler 2.1.3
Cannot spawn dotnet spawn dotnet ENOENT
× ｢wdm｣: Hash: 298e4eed64b27064bb4a
Version: webpack 4.25.1
Time: 616ms
Built at: 2019-01-03 12:03:21
    Asset     Size  Chunks             Chunk Names
bundle.js  343 KiB    main  [emitted]  main
Entrypoint main = bundle.js
[0] multi (webpack)-dev-server/client?http://localhost:8080 ./src/App.fsproj 40 bytes {main} [built]
[./node_modules/ansi-html/index.js] 4.16 KiB {main} [built]
[./node_modules/events/events.js] 8.13 KiB {main} [built]
[./node_modules/html-entities/index.js] 231 bytes {main} [built]
[./node_modules/loglevel/lib/loglevel.js] 7.68 KiB {main} [built]
[./node_modules/node-libs-browser/node_modules/punycode/punycode.js] 14.3 KiB {main} [built]
[./node_modules/querystring-es3/index.js] 127 bytes {main} [built]
[./node_modules/url/url.js] 22.8 KiB {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 7.78 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.58 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {main} [built]
[./node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {main} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {main} [built]
[./src/App.fsproj] 485 bytes {main} [built] [failed] [1 error]
    + 11 hidden modules

ERROR in ./src/App.fsproj
Module build failed (from ./node_modules/fable-loader/index.js):
Error: write EPIPE
    at Loader.getCompiler.send.then.catch.err (G:\workspace_react\tutorials\fable2-samples-master\minimal\node_modules\fable-loader\index.js:121:18)
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/App.fsproj main[1]
i ｢wdm｣: Failed to compile.
```
I have not found an answer for the moment to my problem. Can you help me solve it please?

For information, package.json contains :
```
{
  "private": true,
  "scripts": {
    "start": "webpack-dev-server"
  },
  "dependencies": {
    "@babel/core": "^7.1.2",
    "fable-compiler": "^2.1.3",
    "fable-loader": "^2.1.0",
    "webpack": "^4.25.1",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.10",
    "react": "^16.6.0",
    "react-dom": "^16.6.0"
  }
}
```

OS : windows 10
nodejs version : 8.11.2
npm version : 5.6.0

Thanks

**Comment by et1975** [comment]
do you have `dotnet` sdk installed? What does `dotnet --info` say?

EDIT: if you run the build (.sh or .cmd) it will install one for you and bring all other required dependencies.

**Comment by MangelMaxime** [comment]
Also, it seems that your console logs are for fable2-samples not this repo.

**Comment by et1975** [comment]
Please bring this up fable2-samples repo if you still have a problem.
